<form action="/users" method="get">
    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
    <input type="submit" value="Search" />
</form>
<table>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td>
                <?php
                if (strpos($user['nickname'], $term) !== false) :
                    echo (htmlspecialchars($user['nickname']));
                endif;
                ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>
<h1>Зарегистрированные пользователи</h1>
<table>
    <tr>
        <?php foreach ($users[0] as $key => $value) : ?>
            <td>
                <h3><?= $key   ?></h3>
            </td>
        <?php endforeach ?>
    </tr>
    <?php foreach ($users as $user) : ?>

        <tr>
            <td>
                <p><?= htmlspecialchars($user['id']) ?></p>
            </td>
            <td>
                <p><?= htmlspecialchars($user['nickname']) ?></p>
            </td>
            <td>
                <p><?= htmlspecialchars($user['email']) ?></p>
            </td>
        </tr>
    <?php endforeach ?>
</table>