<form action="/users" method="post">
    <div>
        <label>
            Никнейм
            <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']) ?>">
        </label>
        <?php if (isset($errors['nickname'])) : ?>
            <div><?= $errors['nickname'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Email
            <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
        </label>
        <?php if (isset($errors['email'])) : ?>
            <div><?= $errors['email'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            id
            <input type="text" name="user[id]" readonly value="<?= htmlspecialchars(uniqid()) ?>">
        </label>
    </div>
    <input type="submit" value="Sign Up">
</form>