<form action="/users" method="post">
    <div>
        <label>
            Никнейм
            <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['name']) ?>">
        </label>
        <?php if (isset($errors['name'])) : ?>
            <div><?= $errors['name'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Email
            <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
        </label>
        <?php if (isset($errors['email'])) : ?>
            <div><?= $errors['email'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            id
        </label>
    </div>
    <input type="submit" value="Sign Up">
</form>